# File: migrations/script.py.mako
"""baseline schema

Revision ID: 1553424468b9
Revises: 
Create Date: 2026-08-18 10:39:59.457236
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1553424468b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index('ix_articles_category', 'articles', ['category'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['published'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('player', sa.String(length=100), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_team'), 'match_events', ['team'], unique=False)
    op.create_table('team_stats',
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('gf_rolling', sa.Float(), nullable=False),
    sa.Column('ga_rolling', sa.Float(), nullable=False),
    sa.Column('sh_rolling', sa.Float(), nullable=False),
    sa.Column('sot_rolling', sa.Float(), nullable=False),
    sa.Column('dist_rolling', sa.Float(), nullable=False),
    sa.Column('fk_rolling', sa.Float(), nullable=False),
    sa.Column('pk_rolling', sa.Float(), nullable=False),
    sa.Column('pkatt_rolling', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_match_events_team'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_articles_published', table_name='articles')
    op.drop_index('ix_articles_category', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
