# File: migrations/script.py.mako
"""add chat message user id

Revision ID: 1f0979b98109
Revises: ab6191b0d326
Create Date: 2026-08-18 11:37:44.177141
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0979b98109'
down_revision: Union[str, None] = 'ab6191b0d326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###
