# File: migrations/script.py.mako
"""add xg xga poss rolling stats

Revision ID: ab6191b0d326
Revises: 1553424468b9
Create Date: 2026-08-18 10:57:58.076800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6191b0d326'
down_revision: Union[str, None] = '1553424468b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default required: Postgres refuses NOT NULL columns on populated tables
    op.add_column('team_stats', sa.Column('xg_rolling', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('team_stats', sa.Column('xga_rolling', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('team_stats', sa.Column('poss_rolling', sa.Float(), nullable=False, server_default='0.0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_stats', 'poss_rolling')
    op.drop_column('team_stats', 'xga_rolling')
    op.drop_column('team_stats', 'xg_rolling')
    # ### end Alembic commands ###
