# File: migrations/script.py.mako
"""add call review jobs table

Revision ID: b0d450392fc9
Revises: 1f0979b98109
Create Date: 2026-08-18 17:03:21.784621
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d450392fc9'
down_revision: Union[str, None] = '1f0979b98109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=1000), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('competition', sa.String(length=100), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_jobs_status'), 'call_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_jobs_status'), table_name='call_jobs')
    op.drop_table('call_jobs')
    # ### end Alembic commands ###
